Multi-arch support (#203)
* Introduce multi-arch support with experimental pack CLI

* Push image with skopeo

* Create release: test on both architectures

* cleanup todos

* Use official Procfile buildpack

* use multi-arch all

* pack publish to version tag instead of latest

* Vendor in experimental pack binaries temporarily

* remove unused function from smoke.sh

* update .syncignore

* add smoke test roundup step

diff --git a/.github/workflows/test-pull-request.yml b/.github/workflows/test-pull-request.yml
--- a/.github/workflows/test-pull-request.yml
+++ b/.github/workflows/test-pull-request.yml
@@ -6,10 +6,13 @@ on:
     - main
 
 jobs:
-
   smoke:
-    name: Smoke Test
-    runs-on: ubuntu-22.04
+    name: Architecture-Specific Smoke Test
+    runs-on: ${{ matrix.runner }}
+    strategy:
+      matrix:
+        runner: [ ubuntu-22.04, buildjet-4vcpu-ubuntu-2204-arm ]
+
     steps:
     - name: Setup Go
       uses: actions/setup-go@v3
@@ -21,6 +24,23 @@ jobs:
 
     - name: Run Smoke Tests
       run: ./scripts/smoke.sh
+
+
+  roundup:
+    name: Smoke Test
+    if: ${{ always() }}
+    runs-on: ubuntu-22.04
+    needs: smoke
+    steps:
+    - run: |
+        result="${{ needs.smoke.result }}"
+        if [[ $result == "success" ]]; then
+          echo "Smoke tests passed against all builders"
+          exit 0
+        else
+          echo "Smoke tests failed on one or more builders"
+          exit 1
+        fi
 
   upload:
     name: Upload Workflow Event Payload
